import {Product} from '../model/types';

export const PRODUCTS_LIST: Product[] = [
  {
    category: 'Phones',
    brand: 'Apple',
    model: 'iPhone 6',
    variant: '128GB',
    total: 207,
  },
  {
    category: 'Phones',
    brand: 'Apple',
    model: 'iPhone 6',
    variant: '256GB',
    total: 136,
  },
  {
    category: 'Phones',
    brand: 'Apple',
    model: 'iPhone 6',
    variant: '512GB',
    total: 59,
  },
  {
    category: 'Phones',
    brand: 'Apple',
    model: 'iPhone 7',
    variant: '128GB',
    total: 59,
  },
  {
    category: 'Phones',
    brand: 'Apple',
    model: 'iPhone 7',
    variant: '256GB',
    total: 136,
  },
  {
    category: 'Phones',
    brand: 'Apple',
    model: 'iPhone 7',
    variant: '512GB',
    total: 59,
  },
  {
    category: 'Phones',
    brand: 'Samsung',
    model: 'Galaxy A52',
    variant: '128GB',
    total: 28,
  },
  {
    category: 'Phones',
    brand: 'Samsung',
    model: 'Galaxy A52',
    variant: '256GB',
    total: 301,
  },
  {
    category: 'Phones',
    brand: 'Samsung',
    model: 'Galaxy A52',
    variant: '512GB',
    total: 211,
  },
  {
    category: 'Phones',
    brand: 'Samsung',
    model: 'Galaxy S21',
    variant: '256GB',
    total: 2538,
  },
  {
    category: 'Watches',
    brand: 'Apple',
    model: 'Apple Watch SE GPS',
    variant: '40mm',
    total: 96,
  },
  {
    category: 'Watches',
    brand: 'Apple',
    model: 'Apple Series 7',
    variant: '45mm',
    total: 112,
  },
  {
    category: 'Watches',
    brand: 'Apple',
    model: 'Apple Series 7',
    variant: '41mm',
    total: 12,
  },
  {
    category: 'Watches',
    brand: 'Samsung',
    model: 'Galaxy Watch 4',
    variant: '40mm',
    total: 212,
  },
  {
    category: 'Watches',
    brand: 'Samsung',
    model: 'Galaxy Watch 4',
    variant: '46mm',
    total: 317,
  },
  {
    category: 'Computers',
    brand: 'Apple',
    model: 'MacBook Air',
    variant: 'RAM 16GB',
    total: 57,
  },
  {
    category: 'Computers',
    brand: 'Apple',
    model: 'MacBook Air',
    variant: 'RAM 32GB',
    total: 107,
  },
  {
    category: 'Computers',
    brand: 'Apple',
    model: 'MacBook Pro',
    variant: 'RAM 32GB',
    total: 107,
  },
  {
    category: 'Computers',
    brand: 'Apple',
    model: 'MacBook Pro',
    variant: 'RAM 64GB',
    total: 207,
  },
  {
    category: 'Computers',
    brand: 'Samsung',
    model: 'NP-NC215-A01',
    variant: 'RAM 2GB',
    total: 207,
  },
  {
    category: 'Computers',
    brand: 'Samsung',
    model: 'NP-NC215-A01',
    variant: 'RAM 8GB',
    total: 77,
  },
  {
    category: 'Computers',
    brand: 'Samsung',
    model: 'NP300V5A-S04',
    variant: 'RAM 4GB',
    total: 307,
  },
  {
    category: 'Computers',
    brand: 'Samsung',
    model: 'NP300V5A-S04',
    variant: 'RAM 8GB',
    total: 407,
  },
];
